### ISSUE TITLE
VVV/EE Add colours and fonts for seAp

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#13]
##  Description

We need some seAp branding on the site. Here is a link to the designs: https://drive.google.com/file/d/0ByiaMChTtEUWYkMwYnZqWllsVVBybVpyNEZRQ0d5RExaLXV3/view?usp=sharing

## Plan

- [x] Get sign off from client on designs
- [x] Make sure it is accessible and inclusive. Do a sweep of the design 
- [x] Implement colour palette as per Holly's design
- [x] Replace or remove any cases of the default font ' Poppins', and agree or replace a fallback to Arial

##  Acceptance Criteria

- [x] Design looks and feels similar to Holly's design (copy on design pdf can be ignored)
- [x] Text links are underlined
- [x] The fonts displayed are the correct brand fonts (Frutiger), Poppins is not present in any CSS

**Comment by rosejbon** [comment]
We now have colours and fonts for the site. @HedgehogHolly is on holiday today but back in tomorrow and can give specifics. Or @Nikomus may know as he has seen seAp's branding guidelines, I don't seem to have a copy, or it is lost to the ether.

**Comment by HedgehogHolly** [comment]
## Colours

Pink:  #EC008C
Grey: #767676
Yellow: #FAA81C

## Typeface

Frutiger LT Std 


_(It be great to get the exact font file from seAp, I just downloaded a copy online)_

**Comment by AlinChindea** [comment]
@HedgehogHolly Are you happy with me creating a on hover action with lighened/darkened nuance for the icons? Also, do you have the icons from the pdf or can you create an icon file?

**Comment by HedgehogHolly** [comment]
The icons I've used in the designs are leftover from Samaritans (we are **not** allowed to use them for seAp) I was using them just as a placeholder. I think we talked about using previous icon fonts from Haven and other Contemplating Actions projects.   @katjam might know more about where to find those fonts. 

Im happy for you to do any lightened/darkened nuances for the icons if you like :)

**Comment by katjam** [comment]
Yes, I remember!

**Comment by katjam** [comment]
@HedgehogHolly We might want some review of the dynamic styles.

I'm not keen on swapping colours on hover - @AlinChindea maybe try as we discussed lightening or darkening the colour rather than a swap... but consult Holly as it is anyway/

**Comment by jermyk** [comment]
##  Acceptance Criteria

- [x] Design looks and feels similar to Holly's design (copy on design pdf can be ignored)
- [x] Text links are underlined
![Screenshot_012820_113936_AM](https://user-images.githubusercontent.com/4446325/73260899-dd457900-41c2-11ea-957e-af8cf3761183.jpg)

- [x] The fonts displayed are the correct brand fonts (Frutiger), Poppins is not present in any CSS

**Comment by jermyk** [comment]
**Pink: #EC008C**
![Screenshot_012820_021947_PM](https://user-images.githubusercontent.com/4446325/73271841-420bce00-41d9-11ea-8918-b711ef4e8f74.jpg)

**Grey: #767676**
![Screenshot_012820_021454_PM](https://user-images.githubusercontent.com/4446325/73271458-8ea2d980-41d8-11ea-9715-be5ae6320f96.jpg)

**Yellow: #FAA81C**
![Screenshot_012820_021651_PM](https://user-images.githubusercontent.com/4446325/73271643-db86b000-41d8-11ea-861c-5479cfa9a464.jpg)

**Comment by rosejbon** [comment]
We are  happy with the colours as they look and feel like Holly's design
