### ISSUE TITLE
VVV/E Add copy for seAp home page

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#14]
## Description 

Copy for home page needs to be added. Copy is here: https://docs.google.com/spreadsheets/d/1aFDhogqKhC2AogDuwdOVTlOytb3NxbsYjOaka43ssbw/edit?usp=sharing

## Plan

- [x] Get sign off from client
- [x] Add copy from Google Doc

## Acceptance Criteria

- [x] Copy matches Google Doc

**Comment by jermyk** [comment]
## Acceptance Criteria

- [x] Copy matches Google Doc

**Comment by jermyk** [comment]
![Screenshot_012820_021106_PM](https://user-images.githubusercontent.com/4446325/73271183-07556600-41d8-11ea-9b67-370d081a94e0.jpg)
![Screenshot_012820_021128_PM](https://user-images.githubusercontent.com/4446325/73271203-13d9be80-41d8-11ea-9b5e-04d98def23bf.jpg)
