### ISSUE TITLE
VVV/E Add copy to 'Information to help you' for seAp

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#15]
##  Description

We need to add the bite size information we have written based on the user research we have done to the site. 

Link to the master copy: https://docs.google.com/spreadsheets/d/1aFDhogqKhC2AogDuwdOVTlOytb3NxbsYjOaka43ssbw/edit?usp=sharing

## Plan

- [x] Add copy 

## Acceptance Criteria

- [x] Copy matched the copy in the copy spreadsheet 
- [x] All information is selectable from the 'Information to help you' page
- [x] The order of the information is the same as in the Google Spreadsheet

**Comment by rosejbon** [comment]
Here is a link to the Google doc we worked on with Liz: https://docs.google.com/document/d/19m1wA-KrYkKV8YO-wHm9Htxo7uv3Lfv01ulI_64av6A/edit?usp=sharing

**Comment by jermyk** [comment]
## Acceptance Criteria

- [x] Copy matched the copy in the copy spreadsheet 
- [x] All information is selectable from the 'Information to help you' page
- [x] The order of the information is the same as in the Google Spreadsheet

**Comment by jermyk** [comment]
**What happens when you contact us?**

- [ ] Another word/punctuation required after advice?
![Screenshot_012820_022736_PM](https://user-images.githubusercontent.com/4446325/73272469-556b6900-41da-11ea-8991-abaad632a2d3.jpg)

**Comment by jermyk** [comment]
**Am I just making a fuss?**
 - [x] Have or has?

![Screenshot_012820_023426_PM](https://user-images.githubusercontent.com/4446325/73273084-4933db80-41db-11ea-8614-c759862325a8.jpg)

**Comment by jermyk** [comment]
@AlinChindea Couple of grammatical questions and user was unable to find the 
**"[ CopyText ""We can't find a page with that title, sorry.""
                , CopyText ""Please use the 'Other information to help you' page to see if we have the topic you are looking for.""** text.
                ]"

**Comment by AlinChindea** [comment]
> @AlinChindea Couple of grammatical questions and user was unable to find the
> **"[ CopyText ""We can't find a page with that title, sorry."" , CopyText ""Please use the 'Other information to help you' page to see if we have the topic you are looking for.""** text.
> ]"

@jermyk thanks for letting me know. kindly tag @roseb04 as well for any questions regarding copy doc. I was merely pasting the content from the copy spreadsheet which is not necessarily a good practice.

**Comment by Nikomus** [comment]
@jermyk you'd only encounter that copy if you went to an info page that didn't exist, like this made-up URL:
https://neontribe.github.io/ca-seap/#/info-to-help/some-wrong-url

**Comment by jermyk** [comment]
@Nikomus 

Thank you

![Screenshot_012920_102944_AM](https://user-images.githubusercontent.com/4446325/73349128-8bfcbe80-4282-11ea-898e-c87d34b353eb.jpg)
