### ISSUE TITLE
Add seAp Analytics

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#18]
## Description
We need to add analytics to assess the usage of the site for the project

## Plan
- [x] @roseb04 to agree with seAp how we are going to implement analytics
- [x] Add script to site
- [x] Add fresh index files

## Acceptance Criteria
- [ ] Google Analytics works when users accept the GA cookie
- [ ] GA registers on page load
- [ ] Site title relates to seAp

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Google Analytics works when users accept the GA cookie
- [x] GA registers on page load
- [x] Site title relates to seAp

@AlinChindea 

I can see the google analytics working on the page by viewing in WASP.
![Untitled_Clipping_020520_093938_AM](https://user-images.githubusercontent.com/4446325/73829768-6da33f80-47fb-11ea-9d47-960898d9f745.jpg)

The highlighted area of code in the screenshot is actually highlighted as the user navs through the pages.

Is this evidence enough tp pass this ticket.

I'm unable to see anything in google analytics however?

**Comment by AlinChindea** [comment]
@jermyk I use the GA debugger Chrome extension and I see it working, too but if you are unable to see anything in the GA account maybe we should ask @roseb04 or @katjam to have a look in there before we pass this ticket.

**Comment by rosejbon** [comment]
It looks like its working, it can see me on a page
![image](https://user-images.githubusercontent.com/44296500/73850318-6001b000-4823-11ea-86b4-e2df46d630da.png)

**Comment by rosejbon** [comment]
And it also stops seeing me when I refresh and click reject cookies :)

**Comment by AlinChindea** [comment]
@jermyk I believe we now have enough evidence to pass this ticket. :heavy_check_mark:
