### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#2]
## Description 
We will be looking for up to four stories. These stories will help people overcome those fears or barriers to making a complaint about their care or treatment. SeAp will source up to 4 stories, if possible the quotes to be verbatim. These can be in any format but best for them to follow the below structure and Neontribe will then write up the copy so it fits in with the site.

**If possible to structure stories as follows**:

- "I was in this situation"
- "I was scared/worried/concerned that if I did X, Y might happen - but it didn't"
- "This is what actually happened"
- "Because of this I felt this improvement/was able to do this/etc"

### Plan

- [x] @katquatermass and @roseb04 to source 4 stories from seAp contacts
- [x] Neontribe to edit into the correct format
- [ ] Liz to sign off on stories
- [ ] Send over stories to illustrators to produce accompanying illustrations

**Comment by rosejbon** [comment]
We should ask participants for user research if they would be interested in speaking to us later and sharing their story to inspire other people to make complaints

**Comment by rosejbon** [comment]
Liz is reaching out to advocates to see if they know people who would be willing to share their stories. Shared this doc: https://docs.google.com/document/d/197QiFyCMCtGdZH-iawkHBTSvJiFXdMfeMgKT5trgW4A/edit?usp=sharing

**Comment by rosejbon** [comment]
Updating plan to reflect work @katquatermass and I are doing to source stories

**Comment by rosejbon** [comment]
We nearly have all of the stories, waiting on Liz to decide whether we need to image a 4th scenario because we don't currently have a story from our target group

**Comment by katjam** [comment]
@roseb04 @katquatermass Has Liz signed off on this yet - can we close?

**Comment by katquatermass** [comment]
Yes can close.  I have one minor edit to discuss with Rose on a Seap story that I don't think we need to run by them, and that doesn't affect illustrations.  WE did the 4th imagined scenario.
