### ISSUE TITLE
Reset copy

### ISSUE THREAD

**Issue by Nikomus** [neontribe/ca-seap#21]
## Description
To make sure that no unintentional copy is included in the project, we can change all of the copy to be an easy-to-spot emoji.

## Plan
- [x] Replace the content of all the keys in `BrandCopy.elm` with an appropriate emoji unicode string of your choice, eg "\u(2728)"

## Acceptance Criteria
- [x] ~~There is no text in the site, only emojis (this will need to be tested before the actual copy is added)~~
- [x] There are no :sparkles: emojis left in the text

**Comment by katjam** [comment]
@AlinChindea I agree that we don't need to test this as it is - but what we do need to test is that there are no emojis left in. That is the purpose of them as placeholder copy - to make sure we don't release without 100% legit copy.

**Comment by AlinChindea** [comment]
> @AlinChindea I agree that we don't need to test this as it is - but what we do need to test is that there are no emojis left in. That is the purpose of them as placeholder copy - to make sure we don't release without 100% legit copy.

Ok, I've updated the AC

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] ~~There is no text in the site, only emojis (this will need to be tested before the actual copy is added)~~
- [ ] There are no :sparkles: emojis left in the text

**Comment by jermyk** [comment]
@AlinChindea 

Privacy policy is still missing text
![Screenshot_012820_025006_PM](https://user-images.githubusercontent.com/4446325/73274447-7a151000-41dd-11ea-8cc4-5cc3d7d23a37.jpg)

**Comment by AlinChindea** [comment]
> @AlinChindea
> 
> Privacy policy is still missing text

Indeed. @roseb04 just shared a draft for our review on Slack. she needs sign off from seAp before we upload it. Ignore this for now, there's an open issue that will be addressed and moved to the testing column once text is approved by seAp.

**Comment by jermyk** [comment]
![Screenshot 2020-02-11 at 11 06 23](https://user-images.githubusercontent.com/4446325/74231469-8bbae500-4cbe-11ea-976f-69e52e2d3e89.png)
![Screenshot 2020-02-11 at 11 06 42](https://user-images.githubusercontent.com/4446325/74231487-97a6a700-4cbe-11ea-98e9-bf01c37c896e.png)
