### ISSUE TITLE
VVV/E Add fourth story copy seAp

### ISSUE THREAD

**Issue by AlinChindea** [neontribe/ca-seap#31]
## Description
Follow up on this #23  <- contains addition of first 3 stories. 

We need to add the 4th story we've collected to the site.

Copy can be [found here](https://docs.google.com/spreadsheets/d/1aFDhogqKhC2AogDuwdOVTlOytb3NxbsYjOaka43ssbw/edit#gid=313569089) 

## Plan
- [x] Add 4th story to site

##  Acceptance Criteria

- [x] copy matches the spreadsheet
https://docs.google.com/spreadsheets/d/1aFDhogqKhC2AogDuwdOVTlOytb3NxbsYjOaka43ssbw/edit?ts=5df9f686#gid=1549274551
- [x] four stories are visible on the site

**Comment by jermyk** [comment]
##  Acceptance Criteria

- [x] copy matches the spreadsheet
https://docs.google.com/spreadsheets/d/1aFDhogqKhC2AogDuwdOVTlOytb3NxbsYjOaka43ssbw/edit?ts=5df9f686#gid=1549274551
- [x] four stories are visible on the site

**Comment by jermyk** [comment]
![Screenshot_012820_111249_AM](https://user-images.githubusercontent.com/4446325/73259191-1ed42500-41bf-11ea-8493-2720d27f3559.jpg)

**Comment by jermyk** [comment]
![Screenshot_012820_111551_AM](https://user-images.githubusercontent.com/4446325/73259349-8c805100-41bf-11ea-9f16-4f45628bd7a7.jpg)

**Comment by jermyk** [comment]
![Screenshot_012820_112853_AM](https://user-images.githubusercontent.com/4446325/73260212-5d6adf00-41c1-11ea-9d60-07fe5634fb74.jpg)



![Screenshot_012820_111821_AM](https://user-images.githubusercontent.com/4446325/73259521-e4b75300-41bf-11ea-9506-482ce28deabc.jpg)
