### ISSUE TITLE
seAp - Address the special single/double quotes use

### ISSUE THREAD

**Issue by AlinChindea** [neontribe/ca-seap#33]
## Description
In copy issues, sometimes text pasted from the spreadsheet uses a mixture of single and double quotes (also mix between plain and other types of quotes). These might not be rendered properly on all browsers.  

## Plan
- [ ] test stories in a varied range of browsers
- [ ] fix any issue that might occur

**Comment by katjam** [comment]
Closing won't fix. We did not get to this and decided not important.
