### ISSUE TITLE
Catch Up Call - 10th January 

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#35]
**Attendees:** @roseb04, Liz, Aoife and Sarah
## Agenda

- [x] What are seAp's rebranding launch plans
- [x] Discuss our proposed plans for CA
- [x] What are the steps?
- [x] Font for site, where can we get a copy

## Actions
- [x] Aoife to look into what is available with their non for profit Youtube and Google accounts
- [x] Aoife to see what interests they narrowed down by on Facebook
- [x] @roseb04 to arrange to meet with Aoife to plan social media campaigns end of Jan
- [x] Sarah to send over font zip file
- [x] @roseb04 to pull together copy and images/videos for adverts
- [x] Once staging site is up to share with Liz for final input

## Notes
- Currently they have a non for profit account with Youtube and Google ads that lets them have one free advert, not sure if they are able to pay on top of that
- We want to target the specific areas they work in (Liz has sent these over)
- They want to learn what social media works for them, ie is Facebook better than Youtube etc.
- They want to know what areas people are clicking on the ads

**Comment by rosejbon** [comment]
We had a quick catch up call and agreed that because of rebranding Neontribe we do the adverts on google and youtube. seAp can still do Facebook

**Comment by katjam** [comment]
@roseb04 Did these actions get done? We can close?

**Comment by rosejbon** [comment]
@katjam yes, sorry I shall close away
