### ISSUE TITLE
VV/E Add triangle icons on home page and story end section buttons

### ISSUE THREAD

**Issue by AlinChindea** [neontribe/ca-seap#40]
## Description
Consider implementing the triangle-like icons on home page and in the story-end section as indicated in the [design spec available here](https://drive.google.com/file/d/0ByiaMChTtEUWYkMwYnZqWllsVVBybVpyNEZRQ0d5RExaLXV3/view)

## Plan
- [ ] Check if this is really needed
- [ ] If needed, use the css for the existing triangle icon (e.g. story card, link to read the story icon) and implement as needed

**Comment by katjam** [comment]
Closing. This was not needed.
