### ISSUE TITLE
Testing Issues (SEAP)

### ISSUE THREAD

**Issue by jermyk** [neontribe/ca-seap#42]
Add any issues found &/or questions for SEAP during testing to this ticket.

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/31


- [x] Copy queries

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/13

- [x] Design looks and feels similar to Holly's design - Very vague? I've tested against colours in the ticket so think it's OK?

- [x] AC no. 3 refers to Poppins? 
How does one know it's not present in any CSS, is this "they should be Frutiger, as opposed to Poppins"?

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/23

 - [x] Dianes Story timeline

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/15

- [x] Grammar

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/21

- [x] Privacy policy missing

**Comment by jermyk** [comment]
- [x] Should seAp footer link open in a seperate tab, currently it takes the user away from the site.

**Comment by AlinChindea** [comment]
> #13
> 
> * [x]  AC no. 3 refers to Poppins?
>   How does one know it's not present in any CSS, is this "they should be Frutiger, as opposed to Poppins"?

@jermyk that's right, the font-family used should be Frutiger. if you open the Chrome Developer tools and in the Styles editor you filter for font-family it should show you which font is used. Or use this article as a guidance - https://developers.google.com/web/updates/2013/09/DevTools-answers-What-font-is-that - as it also shows you how to check that the actual font is working. Alternatively, you can use a browser extension and very quickly it will provide you with all the information on the fonts and colours of a web page

- for Chrome - use this https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en
- for Mozilla - use this https://addons.mozilla.org/en-US/firefox/addon/zjm-whatfont/

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-seap/issues/24

- [x] Explain AC no. 3

**Comment by jermyk** [comment]
https://github.com/neontribe/ca-samaritans/issues/10

 - [ ] Phone number on home page differs to copy

**Comment by jermyk** [comment]
- [ ] Should privacy statemanet in cookies message be a link?

![Screenshot_013020_094435_AM](https://user-images.githubusercontent.com/4446325/73437931-1f96c380-4345-11ea-8337-2dd508fc8ca6.jpg)

**Comment by katjam** [comment]
Closing as we have finished and verified these are ok
