### ISSUE TITLE
Browser Testing - seAp

### ISSUE THREAD

**Issue by jermyk** [neontribe/ca-seap#43]
**SUPPORTED BROWSER LIST**
Devices: iPhone, iPad, Android Phone, and desktop
Browsers: Stock Android, Chrome, Safari, Edge, Firefox (latest stable release)

 - [x] Android 4+ Phone - Chrome browser
 - [x] Android 4+ Phone - Firefox Focus browser
 - [x] ipad iOS7+ - Safari browser
 - [x] iphone 5 iOS7+ - Safari browser - **macbook simulator**
 - [x] iphone 6 iOS7+ - Safari browser - **macbook simulator**
-  [x] iphone 7 iOS7+ - Safari browser - **macbook simulator**
 - [x] Desktop - Chrome browser
 - [x] Desktop - Firefox browser

**Comment by jermyk** [comment]
@katjam 

I'll write a script for this as I complete browser testing.

https://github.com/neontribe/contemplating-action/issues/259

Check for - 
- [x] special char single or double quotes - e.g. double quotes within double quotes - are rendered ok on all browsers - carded in #33 for potential follow up

**Comment by jermyk** [comment]
@AlinChindea  fyi.
- [x] Android - **Chrome browser** Samsung Galaxy SM-J600FN

![Screenshot_013020_050314_PM](https://user-images.githubusercontent.com/4446325/73472095-67880b80-4382-11ea-9a80-9349f4f091fa.jpg)

![Screenshot_013020_050638_PM](https://user-images.githubusercontent.com/4446325/73472393-e0876300-4382-11ea-89b3-aa739b58b177.jpg)

**Same applies to Firefox Focus**


**iPad**
![Screenshot_013120_104539_AM](https://user-images.githubusercontent.com/4446325/73533542-fe060c80-4416-11ea-9d64-c6a86bfb7c69.jpg)

These will be fixed as part of Will be fixed as part of https://github.com/neontribe/ca-samaritans/issues/54

**Comment by katjam** [comment]
hmmm. those should be set to wrap multi line.

**Comment by katjam** [comment]
Maybe it's a difference in font size that tips the algorithm? Or maybe the core styles aren't applied?

**Comment by jermyk** [comment]
@katja 
They're fine in landscape mode

**Comment by jermyk** [comment]
@katjam Are we doing android stock browser?

**Comment by jermyk** [comment]
@AlinChindea @katjam 

I'm noticing that the site is slow to respond on the iPad. 
Could you take a look too please (assuming you have one). I want to rule out user error this end?
Thanks.

**Comment by jermyk** [comment]
- [x] Does the lozenge and image look a bit crowded?

![image](https://user-images.githubusercontent.com/4446325/73545967-47188980-4434-11ea-8d83-578a6d1a50d4.png)

Will be fixed as part of https://github.com/neontribe/ca-samaritans/issues/54

**Comment by jermyk** [comment]
- [x] iPhone 5 renders lozenges correctly
![image](https://user-images.githubusercontent.com/4446325/73546079-7cbd7280-4434-11ea-876f-67a6f3129007.png)

**Comment by jermyk** [comment]
- [x] iPhone 7 renders correctly on one line, if a little right aligned.
![image](https://user-images.githubusercontent.com/4446325/73547849-a926be00-4437-11ea-8710-508e81539a5f.png)

**Comment by jermyk** [comment]
- [x] But not for all lozenges?
![image](https://user-images.githubusercontent.com/4446325/73548261-5e597600-4438-11ea-81fe-78d31690f565.png)

Will be fixed as part of https://github.com/neontribe/ca-samaritans/issues/55

**Comment by jermyk** [comment]
@AlinChindea @katjam 
Browser testing complete. A few styling issues but funcionality seems OK.

I need to do a quick review once the privacy policy is added.

**Comment by Nikomus** [comment]
@jermyk The info stories at the bottom seem to not wrap unless 50% on the last word goes out of bounds of the page, not the container. Easier to see with some different colours:
![image](https://user-images.githubusercontent.com/32434620/74171170-08e64b80-4c26-11ea-86da-f7d5a74049cc.png)

It should be to do with this CSS:
![image](https://user-images.githubusercontent.com/32434620/74171227-1f8ca280-4c26-11ea-8239-bb0a87bd1970.png)

**Comment by katjam** [comment]
Closing as we have released and happy!
