### ISSUE TITLE
Hosting and domain name

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#5]
## Description
We will be handing over to seAp's IT team. They will host and put the site on a subdomain of their new domain

![image](https://user-images.githubusercontent.com/44296500/64602170-3187c200-d3b6-11e9-97d0-bb2e63ef2e31.png)

## Plan 

- [ ] Discuss how to handover to seAp's IT team
- [ ] update Readme, production URL

**Comment by katjam** [comment]
Closing. We went with now and a new domain.
